---
driver:
  name: docker

platforms:
  - name: debian_latest
    image: ghcr.io/x-delfino/molecule-debian_latest:latest
    pre_build_image: true
  - name: debian_bookworm
    image: ghcr.io/x-delfino/molecule-debian_bookworm:latest
    pre_build_image: true
  - name: debian_bullseye
    image: ghcr.io/x-delfino/molecule-debian_bullseye:latest
    pre_build_image: true

  - name: ubuntu_latest
    image: ghcr.io/x-delfino/molecule-ubuntu_latest:latest
    pre_build_image: true
  - name: ubuntu_focal
    image: ghcr.io/x-delfino/molecule-ubuntu_focal:latest
    pre_build_image: true
  - name: ubuntu_jammy
    image: ghcr.io/x-delfino/molecule-ubuntu_jammy:latest
    pre_build_image: true
  - name: ubuntu_noble
    image: ghcr.io/x-delfino/molecule-ubuntu_noble:latest
    pre_build_image: true

  - name: kali_rolling
    image: ghcr.io/x-delfino/molecule-kali_rolling:latest
    pre_build_image: true
  - name: kali_release
    image: ghcr.io/x-delfino/molecule-kali_release:latest
    pre_build_image: true
